# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OONIRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=255)),
                ('test_start_time', models.DateTimeField()),
                ('input_url', models.URLField()),
                ('software_name', models.CharField(max_length=20)),
                ('test_name', models.CharField(max_length=20)),
                ('probe_asn', models.CharField(max_length=10)),
                ('probe_cc', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('OPEN', 'Accessible'), ('BLOCKED', 'Blocked')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('OPEN', 'Not Submitted'), ('SUBMITTED', 'Submitted'), ('REJECTED', 'Rejected')], max_length=20)),
            ],
        ),
    ]
